import { Playwrite_AU_QLD, Roboto_Condensed } from "next/font/google";
import "./globals.css";

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
});

const playwriteAustraliaQLD = Playwrite_AU_QLD({
  variable: "--font-playwrite-australia-queensland",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensed.variable} ${playwriteAustraliaQLD.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
